### ISSUE TITLE
Compile in release mode

### ISSUE THREAD

**Issue by asterite** [wmoxam/crystal-clbg#1]
I noticed the `build` command in the README lacks the `--release` flag. Make sure to always compile with `--release` for production-ready apps or for benchmarks, as this turns on optimizations. Example:

```
crystal build fannkuchredux.cr --release
```

This also applies for this project: https://github.com/alehander42/hackbg-solutions

There's also this project, you might want to take a look at it after you finished implementing your solution. If one of your solutions is faster you could submit a pull request :-)

https://github.com/kostya/crystal-benchmarks-game

**Comment by wmoxam** [comment]
@asterite I didn't know about --release, thanks!

Thanks for pointing out the other implementation. I'll have to take a look when I'm done ;)

**Comment by wmoxam** [comment]
Fixed in 6435f3f69e0f0fa4c7a18f130f9cef5d341d65d8 ;)

**Comment by asterite** [comment]
Thank you! I'll soon update the language's docs and add a chapter for how to use the compiler and probably mention `--release` there so everyone learns about that from the beginning.
